### ISSUE TITLE
Captura de Producción de Polvo Atomizado

### ISSUE THREAD

**Issue by GabyBere** [GabyBere/Incidencias-Manuales#1]
Modificaciones en los 3 demos.
1. Validacion de Densidad.------Completo
2. Validación Desperdicio.--------Incompleto
3. Consumo Energético.---------Incompleto
Resultado: Satisfactorio.
En el demo de captura de producción de polvo atomizado parte 1 están poniendo densidad de 10 cuyo valor es incorrecto,  no se observa en el demo que se active la validación
se debe cambiar el demo poniendo un valor dentro del rango 1.4 a 1.8
![image](https://cloud.githubusercontent.com/assets/11563662/6815978/a2cda7c8-d252-11e4-9b16-6a1c57d5ea68.png)

**Comment by GabyBere** [comment]
5 - En el demo parte 2 de captura de producción de polvo atomizado tiene el mismo error en la captura de densidad con el agravante de que se captura tiempo de producción cero y se captura desperdicio.
![image](https://cloud.githubusercontent.com/assets/11563662/6816031/71f35caa-d253-11e4-9872-8890c1d7bede.png)

Se sugiere que la parte 2 contenga la versión de captura de producción con la variante de calculo de producción por el metodo del rendimiento
y tambien agregar ya sea en el demo parte 1 o parte 2  la captura de consumo energético.

**Comment by GabyBere** [comment]
7 - En el demo parte 3 de captura de producción de polvo atomizado se muestra un ejemplo con la variante de calculo de producción con el método de rendimiento
sin embargo está mal el ejemplo ya que capturan un tiempo de producción de 0 minutos y por otro lado se capturan tolvas de desperdicio,
esto no debe ser posible en la práctica cotidiana. Si no hay producción no puede haber desperdicio, 
![image](https://cloud.githubusercontent.com/assets/11563662/6816092/17192bb0-d254-11e4-8fcc-4ca0d1166f80.png)

**Comment by mtrejo30** [comment]
Validar en documentación
