### ISSUE TITLE
Demo para consulta de reportes

### ISSUE THREAD

**Issue by GabyBere** [GabyBere/Incidencias-Manuales#6]

**Comment by GabyBere** [comment]
Reportes - Producción

Resultado: Satisfactorio.
1. Barbotina Y Polvo Atomizado
2. Consumo Defloculante
3. Humedades Barbotina
4. Consumos Energéticos

**Comment by GabyBere** [comment]
Reportes - Existencias

Resultado: Incompleto
1. Barbotina - Polvo Atomizado
2.  Archivos XML --------------------------------- Incompleto,( no se puede en explorer y en Chrome si.)
3. Diferencias en Inventario
4. Empaque y Embalaje
5.  Esmaltes y Compuestos
6.  Log de Transacciones
7. Materia Prima Esmaltes
8. Ejecutivo de Avance
9. Log de Máquinas

**Comment by GabyBere** [comment]
Reportes - Tiempos Muertos

Resultado: Satisfactorio
1. Por Causa
2. Por Máquina
3. Tipo de Paro
4. Total

**Comment by GabyBere** [comment]
1.  Archivos XML --------------------------------- Incompleto,( no se puede en explorer y en Chrome)
   se realizo en Productivo. No en QA
- Explorer.
  ![image](https://cloud.githubusercontent.com/assets/11563662/6809485/4571b4e8-d220-11e4-9002-b1075d0dee3d.png)

*Chrome

![image](https://cloud.githubusercontent.com/assets/11563662/6809493/527aaf14-d220-11e4-8f2f-aebd57c2899a.png)

**Comment by mtrejo30** [comment]
Es cuestión del explorador en cualquier otro y superior a IE8 funciona correctamente

**Comment by GabyBere** [comment]
![image](https://cloud.githubusercontent.com/assets/11563662/6859914/0593cc1e-d3e5-11e4-9153-ec563c7eb329.png)
